### ISSUE TITLE
"App crashed - waiting for file changes before starting" error

### ISSUE THREAD

**Issue by designeng** [SC5/cerebellum#19]
After running `npm run build`, `npm start` here's the error message:
```
designeng@kasmu static-pages (master) $ npm run build

> static-pages@1.0.0 build /js/isomorphic/cerebellum/examples/static-pages
> NODE_ENV=production browserify client.js -u jquery -u underscore -t reactify -t envify -o public/js/app.js

designeng@kasmu static-pages (master) $ npm start

> static-pages@1.0.0 start /js/isomorphic/cerebellum/examples/static-pages
> nodemon server.js

[nodemon] 1.8.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/js/isomorphic/cerebellum/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/js/isomorphic/cerebellum/examples/static-pages/server.js:32:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
[nodemon] app crashed - waiting for file changes before starting...
```
Initial `npm start` was successful.

**Comment by designeng** [comment]
Obviously it's a bug (feature?) `nodemon`. After restarting terminal window all is ok.
